joelguittet/mender-mcu-client

- core/src/mender-client.c
- include/mender-client.h
- include/mender-rtos.h
- platform/rtos/freertos/src/mender-rtos.c
- platform/rtos/posix/src/mender-rtos.c
- platform/rtos/zephyr/src/mender-rtos.c
The purpose of this Pull Request is to remove unused works introducing a state machine in the mender client.
To achieve this, a new rtos API is required to update the work period after starting a work.
> client: introduce state machine, remove unused works

- platform/net/zephyr/src/mender-net.c
- zephyr/Kconfig
The purpose of this Pull Request is to add TLS_PEER_VERIFY option to zephyr net implementation.
> net: add TLS_PEER_VERIFY option to zephyr net platform

- platform/tls/mbedtls/src/mender-tls.c
The purpose of this Pull Request is to remove the possibility to customize the mbedtls buffer size, as it is not required to do it.
> platform: remove mbedtls options

- esp-idf/CMakeLists.txt
- platform/net/curl/src/mender-http.c
- platform/net/curl/src/mender-websocket.c
- platform/net/esp-idf/src/mender-http.c
- platform/net/esp-idf/src/mender-websocket.c
- platform/net/zephyr/src/mender-http.c
- platform/net/zephyr/src/mender-websocket.c
- zephyr/CMakeLists.txt
The purpose of this Pull Request is to add User-Agent header support.
> platform: add user agent header

- add-ons/src/mender-configure.c
- add-ons/src/mender-inventory.c
- core/src/mender-client.c
- esp-idf/Kconfig
- include/mender-client.h
- include/mender-configure.h
- include/mender-inventory.h
- include/mender-rtos.h
- include/mender-troubleshoot.h
- platform/rtos/freertos/src/mender-rtos.c
- platform/rtos/posix/src/mender-rtos.c
- platform/rtos/zephyr/src/mender-rtos.c
- zephyr/Kconfig
The purpose of this Pull Request is to add APIs allowing the application to trigger works (authentication/update/inventory/configure).
Additionally, it is possible to disable the periodic execution of works by configuration, so both feature together permit to handle triggering of the execution of the mender client from the application.
Works are still executed from the mender work queue thread inside the rtos module to ensure priorities, stack size etc that are guaranteed by the rtos module scheduler.
The troubleshooting work cannot be stopped and triggered from the applications. There is no interest for that because it is a pure internal work to perform keep alive with the mender server.
This Pull Request replaces https://github.com/joelguittet/mender-mcu-client/pull/19 and offers a …
> client: allow application triggering works

- core/src/mender-api.c
- core/src/mender-client.c
- include/mender-api.h
- include/mender-tls.h
- platform/tls/mbedtls/src/mender-tls.c
The purpose of this Pull Request is to modify the API of the mender-tls module to keep authentication keys inside the module instead of managing this in the client and api levels.
This is to prepare new mender-tls options such as secure element integration.
> platform: keep authentication keys inside the tls module

- .clang-format-ignore
- CMakeLists.txt
- tests/mocks/esp-idf/CMakeLists.txt
- tests/mocks/zephyr/include/version.h
- tests/mocks/zephyr/include/zephyr/net/socket.h
The purpose of this Pull Request is to fix error in the build workflow introduced during the introduction of the user-agent of http/websocket modules.
> tests: fix workflow errors

- platform/rtos/posix/src/mender-rtos.c
The purpose of this Pull Request is to remove the obsolete `usleep` function used in platform rtos posix implementation. `nanosleep` is recommended by SonarCloud.
> platform: remove obsolete usleep function

- core/src/mender-client.c
The purpose of this Pull Request is to handle authentication failure degraded case. It has been observed with a buggy artifact that was needed to rollback while authentication with the mender server fails due to invalid mender server URL.
> client: return error in case the authentication is not done

- platform/rtos/freertos/src/mender-rtos.c
- platform/rtos/posix/src/mender-rtos.c
- platform/rtos/zephyr/src/mender-rtos.c
The purpose of this Pull Request is to handle rtos deactivate blocking situation in case a work is not activated yet.
In this case, the `sem_handle` used to protect the work function is not given and taking the `sem_handle` is blocking (dead lock).
A boolean `activated` flag has been added to handle this condition.
> platform: rtos: permit deactivate if not activated

- platform/net/zephyr/src/mender-net.c
- tests/mocks/zephyr/include/zephyr/net/socket.h
- tests/mocks/zephyr/src/socket.c
- zephyr/Kconfig
The purpose of this Pull Request is to remove usage of posix functions in the platform network zephyr implementation, and prefer zephyr native apis. This remove the dependency to `CONFIG_NET_SOCKETS_POSIX_NAMES`.
> platform: net: zephyr: remove usage of posix apis, prefer using zephyr native functions

- README.md
- add-ons/src/mender-configure.c
- core/src/mender-api.c
- core/src/mender-client.c
- core/src/mender-utils.c
- include/mender-client.h
- include/mender-storage.h
- include/mender-utils.h
- platform/storage/esp-idf/nvs/src/mender-storage.c
- platform/storage/generic/weak/src/mender-storage.c
- platform/storage/posix/src/mender-storage.c
- platform/storage/zephyr/nvs/src/mender-storage.c
- tests/src/main.c
The purpose of this Pull Request is to add support to update modules (#40)
No examples are available at the moment. To use modules, the module type should be registered to the mender client just after `mender_cleint_init` is called, as shown on the following skeleton:
```
/* Register module-readme artifact type */
if (MENDER_OK != mender_client_register_artifact_type("hello-world", &module_hello_world_cb, false, NULL)) {
mender_log_error("Unable to register 'module-readme' artifact type");
ret = EXIT_FAILURE;
goto RELEASE;
}
```
The callback is used to retrieve module content when a deployment is in progress. Because this mechanism is generic, the mender client doesn't provide much more support and specific application implementation should be done depending of the module.
```
static …
```
> Add support to update modules

- core/src/mender-api.c
- core/src/mender-client.c
- include/mender-api.h
- include/mender-client.h
- tests/src/main.c
The purpose of this Pull Request is to allow using a custom identity instead of forcing only the mac address. This permit to use any field in the identity.
> client: allow custom identity instead of using mac address by default

- include/mender-scheduler.h
- platform/scheduler/freertos/src/mender-scheduler.c
- platform/scheduler/generic/weak/src/mender-scheduler.c
- platform/scheduler/posix/src/mender-scheduler.c
- platform/scheduler/zephyr/src/mender-scheduler.c
The purpose of this Pull Request is to remove unused function in the platform scheduler APIs.
> platform: scheduler: remove unused delay functions

- add-ons/src/mender-configure.c
- add-ons/src/mender-inventory.c
- add-ons/src/mender-troubleshoot.c
- core/src/mender-client.c
- include/mender-addon.h
- include/mender-client.h
- include/mender-configure.h
- include/mender-inventory.h
- include/mender-troubleshoot.h
- tests/src/main.c
The purpose of this Pull Request is to improve management of add-ons giving the control to the mender client itself instead of relying on user application.
A new function `mender_client_register_addon` is introduced to register the wanted add-on to the mender client. It will then manage init/activation/deactivation/exit for each add-on.
Particularly, the inventory and configure add-ons are now only managed by mender-client. Only the mender-troubleshoot add-on has an optional activation still controlled by the user application (because this mean connecting to the network and keeping the connection opened, so it's better to let control).
This enhancement permits additional user custom add-ons to be created and registered to the mender-client, for example to manage specific artifact types.
> client: rework apis so that the mender-client registers add-ons and manage them

- add-ons/src/mender-configure.c
The purpose of this Pull Request is to fix a memory issue while parsing the artifact name of the mender-configure add-on. The memory was used after freed. Now a copy of the artifact name is kept if defined.
> addon: configure: fix management of artifact name

- add-ons/src/mender-configure.c
- add-ons/src/mender-inventory.c
- add-ons/src/mender-troubleshoot.c
- core/src/mender-client.c
- include/mender-client.h
- tests/src/main.c
The purpose of this Pull Request it to add network connect/disconnect callback in the mender client so that the mender client can indicate when the network access is required, and when it can be released. This can be used to close network connection when it is not required.
> core: client: add network connect/disconnect callbacks

- add-ons/src/mender-configure.c
- add-ons/src/mender-inventory.c
The purpose of this Pull Request is to remove unused labels. This can cause build error depending of the compiler and depending of the compiler configuration. The issue has been observed on es-idf framework.
> fix: remove unused labels

- core/src/mender-api.c
- core/src/mender-artifact.c
- core/src/mender-client.c
- core/src/mender-utils.c
- include/mender-tls.h
Just some typos that I found while reading the code :+1:
> Fix a bunch of typos in core and include files

- core/src/mender-api.c
Reverts joelguittet/mender-mcu-client#68, as discussed with @lluiscampos this API is only available with Enterprise solution.
The goal is to keep the compatibility with the Open-Source server so we need to keep v1 API.
> Revert "core: update deployment api to v2"

- .github/workflows/ci.yml
- add-ons/src/mender-configure.c
- add-ons/src/mender-inventory.c
- add-ons/src/mender-troubleshoot.c
- core/src/mender-api.c
- core/src/mender-artifact.c
- core/src/mender-client.c
- core/src/mender-utils.c
- include/mender-api.h
- include/mender-artifact.h
- include/mender-client.h
- include/mender-http.h
- include/mender-scheduler.h
- include/mender-storage.h
- platform/flash/posix/src/mender-flash.c
- platform/net/esp-idf/src/mender-http.c
- platform/net/esp-idf/src/mender-websocket.c
- platform/net/generic/curl/src/mender-http.c
- platform/net/generic/curl/src/mender-websocket.c
- platform/net/generic/weak/src/mender-http.c
- platform/net/zephyr/src/mender-http.c
- platform/net/zephyr/src/mender-websocket.c
- platform/shell/zephyr/src/mender-shell.c
- platform/storage/posix/src/mender-storage.c
- platform/tls/generic/cryptoauthlib/src/mender-tls.c
- platform/tls/generic/mbedtls/src/mender-tls.c
- tests/src/main.c
Ubuntu 20.04 used in CI was getting a bit dated.
Updated CI job with latest Ubuntu LTS release (with newer `clang-format`) and format all the code accordingly.
> Update code format with newer `clang-format` tool

- core/src/mender-api.c
The purpose of this Pull-Request is to fix the "Current software" display on mender interface. This issue was reported at https://github.com/joelguittet/mender-mcu-client/issues/69
> api: add rootfs-image.version to fix device display

- .github/workflows/ci.yml
The purpose of this Pull Request is to fix a warning `cmake: /usr/local/lib/libcurl.so.4: no version information available` due to build options of curl.
> ci: fix curl build option to enable versioned symbol

- tests/valgrind_suppression_timer_create.supp
The purpose of this Pull Request is to fix valgrind suppression file used for testing. The update is required following update to ubuntu 24.04.
> tests: update valgrind supression file following update of the ci to uuntu-24.04

- core/src/mender-client.c
The Mender Client used to check if the downloaded artifact was already installed in the past. However, this check was removed in [mendersoftware/mender@1fb6223](https://github.com/mendersoftware/mender/commit/1fb62236abdee6d2ed2452592d289320aea1bfa5) as it prevents the use of the "Force update" option, allowing a device to take part in the same deployment twice. Today, all the "already-installed" logic is performed in the backend.
> Do not check if artifact is already installed

- add-ons/troubleshoot/src/mender-troubleshoot-file-transfer.c
The purpose of this Pull-Request is to fix a double call to close() callback when an error occurred during writing to a file.
> add-ons: troubleshoot: fix to avoid closing file twice when an error occurred during writing

- platform/storage/zephyr/nvs/src/mender-storage.c
- zephyr/Kconfig
The purpose of this Pull Request is to introduce configuration of Zephyr NVS IDs in Kconfig.
> platform: storage: zephyr: nvs: introduce possibility to configure ids

- platform/storage/zephyr/nvs/src/mender-storage.c
- tests/CMakeLists.txt
- tests/mocks/zephyr/include/zephyr/storage/flash_map.h
- zephyr/Kconfig
The purpose of this Pull-Request is to remove the redundant configuration option `CONFIG_MENDER_STORAGE_NVS_SECTOR_COUNT`. This value can be calculated from the partition size and the sector size.
> platform: storage: zephyr: nvs: remove redundant configuration option

- esp-idf/Kconfig
- platform/net/esp-idf/src/mender-websocket.c
- platform/net/generic/curl/src/mender-websocket.c
- platform/net/zephyr/src/mender-websocket.c
- platform/scheduler/freertos/src/mender-scheduler.c
- platform/scheduler/posix/src/mender-scheduler.c
- platform/scheduler/zephyr/src/mender-scheduler.c
- platform/shell/zephyr/src/mender-shell.c
- zephyr/Kconfig
The purpose of this Pull-Request is to modify stack size granularity so that we have a better/finest control of the memory allocated. This also avoid multiple runtime multiplications to convert kilo-bytes to bytes.
> platform: modify stack size granularity from kilo-bytes to bytes
