joelguittet/mender-mcu-client

.github/workflows/check_include_guards.sh, include/mender-api.h, include/mender-client.h, include/mender-common.h, include/mender-http.h, include/mender-log.h, include/mender-ota.h, include/mender-rtos.h, include/mender-storage.h, include/mender-tls.h, include/mender-untar.h, include/mender-utils.h
This Pull-Request adds support of C++ linkage support.
Fixes #5.
=> headers: add c++ linkage support

README.md, esp-idf/Kconfig, include/mender-log.h, platform/board/esp-idf/src/mender-log.c, platform/board/posix/src/mender-log.c, platform/board/zephyr/src/mender-log.c, zephyr/Kconfig
The purpose of this Pull Request is to enhance the log level configuration.
It is now possible to easily customize the log level and reduce the size of the client.
On esp-idf platform a new menu is added to select the log level.
=> logs: enhancement of log level configuration

platform/net/zephyr/src/mender-net.c
The purpose of this Pull Request is to remove the loops introduced at the beginnings to try resolving the host / connecting to the host multiple times in case of failure, on the Zephyr platform.
Indeed, this is not helping when there are issues.
=> net: remove attempt to perform connection multiple times

README.md
The purpose of this Pull Request is to add references and update the contributing section of the README.
=> readme: add references and updates

add-ons/src/mender-troubleshoot.c
The purpose of this Pull Request is to add mender-client handling in the troubleshoot add-on. Two messages are available: `check-update` to trigger execution of the update work and `send-inventory` to trigger sending the inventory to the server.
=> troubleshoot: add handling mender-client messages

platform/net/esp-idf/src/mender-http.c
The purpose of this Pull Request is to have a better handling of chunked response in the platform esp-idf http implementation.
This Pull Request should fix the issue reported at #15 and is inspired of the unfinished correction proposed at #16.
=> platform: better handling of chunked responses from esp-idf http client

.github/workflows/build_tests.sh, CMakeLists.txt, include/mender-websocket.h
The purpose of this Pull Request is to improve cmake integration to create mender-mcu-client library. This prepare landing of #41.
=> Improvment of the cmake integration

core/src/mender-utils.c
The purpose of this Pull Request is to fix a bug not fired previously in the formatting of an error log.
=> utils: fix formatting of an error log

core/src/mender-client.c
The purpose of this Pull Request is to improve the management of the server host and tenant token parameters of the client.
It also fix an issue with empty, not null, tenant token on ESP-IDF environment, reported at https://github.com/joelguittet/mender-esp32-example/issues/12.
=> client: improve management of server host ant tenant token

core/src/mender-api.c, core/src/mender-artifact.c, platform/flash/posix/src/mender-flash.c, platform/net/esp-idf/src/mender-http.c, platform/net/esp-idf/src/mender-websocket.c, platform/net/generic/curl/src/mender-http.c, platform/net/generic/curl/src/mender-websocket.c, platform/net/zephyr/src/mender-http.c, platform/net/zephyr/src/mender-websocket.c, platform/tls/generic/cryptoauthlib/src/mender-tls.c, platform/tls/generic/mbedtls/src/mender-tls.c
The purpose of t his Pull Request is to remove usage of unsafe `sprintf` function, and prefer `snprintf` function instead.
=> client: remove usage of unsafe sprintf function

core/src/mender-artifact.c
The purpose of this Pull Request is to fix memory leak in mender-artifact reported at https://github.com/joelguittet/mender-mcu-client/issues/39
=> core: artifact: fix memory leak while processing artifact file names

add-ons/src/mender-configure.c
The purpose of this Pull Request is to fix a double free issue in mender-configure.
=> add-ons: configure: fix double free error

add-ons/src/mender-configure.c, add-ons/src/mender-inventory.c
The purpose of this Pull Request is to fix some missing re-initialization when exit function is called.
=> addons: add missing re-initializations

core/src/mender-client.c
The purpose of this Pull Request is to improve the management of artifact types list in the mender-client.
=> core: client: improve management of artifact types list

core/src/mender-client.c
The purpose of this Pull Request is to fix a memory leak in the mender-client introduced in a previous commit and reported by sonarcloud after analysis of the master branch.
=> core: client: fix memory leak reported by sonarcloud

platform/flash/esp-idf/src/mender-flash.c
The purpose of this Pull Request is to fix a cast issue reported by sonarcloud.
=> platform: flash: esp-idf: fix cast issue reported by sonarcloud

core/src/mender-api.c
The purpose of the Pull Request is to update deployment API to v2. This can allow future enhancement to POST additional data.
=> core: update deployment api to v2

.github/workflows/ci.yml
The purpose of this Pull-Request is to update curl version used in the CI to the latest available release. Tests have been done on posix platform to ensure no regression is observed.
=> ci: update curl to the latest release

core/src/mender-client.c
The purpose of this Pull Request is to fix degraded condition occurring if the deployment data are invalid on reboot.
In this case the strategy is to delete deployment data and reboot. The booloader will rollback the application.
=> client: reboot to perform rollback if deployment data are invalid

.clang-format-ignore, .gitignore, tests/CMakeLists.txt, tests/mocks/cjson/CMakeLists.txt, tests/mocks/cryptoauthlib/CMakeLists.txt, tests/mocks/cryptoauthlib/include/atca_basic.h, tests/mocks/cryptoauthlib/include/atca_helpers.h, tests/mocks/cryptoauthlib/include/atca_status.h, tests/mocks/cryptoauthlib/include/calib/calib_command.h, tests/mocks/cryptoauthlib/include/cryptoauthlib.h, tests/mocks/cryptoauthlib/src/atca_basic.c, tests/mocks/cryptoauthlib/src/atca_helpers.c, tests/mocks/freertos/CMakeLists.txt, tests/mocks/mbedtls/CMakeLists.txt
The purpose of this Pull Request is to improve cryptoauthlib mocks and cmake fetch content usage.
=> tests: improve management of mocks

esp-idf/Kconfig, platform/tls/generic/cryptoauthlib/src/mender-tls.c, zephyr/Kconfig
The purpose of this Pull Request is to clean the integration of the cryptoauthlib and introduce the configuration of key id in kconfig files.
=> platform: tls: cryptoauthlib: cleaning and configuration in kconfig
